/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef PRESENTATION_PRIVATE_H
#define PRESENTATION_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.0.494"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	494
#define COMPANY_NAME	""
#define FILE_VERSION	"0.0.0.494"
#define FILE_DESCRIPTION	"Main programme"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"0.0.0.494"

#endif /*PRESENTATION_PRIVATE_H*/
